// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cttfjrfjhfmxpiuauxms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0dGZqcmZqaGZteHBpdWF1eG1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTg5MzYsImV4cCI6MjA2MDczNDkzNn0.BpQXA_HKtq4ZMUTdaMTFRPt3pIptX3OLa2EYRH7Ei3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);